### ISSUE TITLE
Bug in computation of transfer function for a timeseries

### ISSUE THREAD

**Issue by madeline-wade** [gwpy/gwpy#1588] opened 2023-02-01 00:35 UTC
The current way that the timeseries object computes a transfer function has a bug in it.  
The current code (https://github.com/gwpy/gwpy/blob/main/gwpy/timeseries/timeseries.py#L1117) has the following:
`csd = other.csd(self, fftlength=fftlength, overlap=overlap,
                        window=window, **kwargs)`

`psd = self.psd(fftlength=fftlength, overlap=overlap, window=window,
                       **kwargs)`

However, this gives a result that is 180 degrees out of phase from the definition of a transfer function.  The transfer function should be computed using:
`csd = self.csd(other, fftlength=fftlength, overlap=overlap, window=window, **kwargs)`
`psd = self.psd(fftlength=fftlength, overlap=overlap, window=window, **kwargs)`

**Comment by duncanmmacleod** [comment] 2023-02-01 08:23
@madeline-wade, thanks for this report. Are you able to post a code snippet that clearly demonstrates the phase offset (mainly to inform a future regression test)?

I have assigned this to @eagoetz (he wrote the original code), hopefully you can work with him to address this.

**Comment by eagoetz** [comment] 2023-02-01 20:39
I concur there is a minor bug. This is a mistake I made because I had misinterpreted the definition of the `csd()` method. I'll put in a fix for this. I confirmed this by comparing the results using DTT

**Closed** 2023-03-21 15:03 UTC
Labels: issue:bug, gwpy.timeseries
