### ISSUE TITLE
ImportError: cannot import name '_get_valid_format' from 'astropy.io.registry' 

### ISSUE THREAD

**Issue by ssalam21** [gwpy/gwpy#1437] opened 2021-11-24 13:45 UTC
I try to read .gwf files by gwpy in the conda environ.  So I use the line 
` from gwpy.timeseries import TimeSeries
from gwpy.time import from_gps
from astropy.time import Time
import numpy as np` 
and the gor the error message  ImportError: cannot import name '_get_valid_format' from 'astropy.io.registry'.

Probably, its the path issue my python path is  `~/Fr/Python/`  and gwpy/astropy has a path here `~/miniconda3/envs/myenv/lib/python3.9/site-packages/astropy/io/registry/__init__.py`. Can anyone suggest me any suggestion/solutions? Thanks

**Comment by duncanmmacleod** [comment] 2021-11-24 13:47
This is a duplicate of #1432, which was fixed in #1435, and will be part of the GWpy-2.1.2 release which should be put out this week.

**Closed by duncanmmacleod** 2021-11-24 13:47 UTC

**Comment by ssalam21** [comment] 2021-11-24 14:18
I've tried with the 'line' provided but can not fix it or I missed something. Can you suggest me something more? Thanks.

**Comment by duncanmmacleod** [comment] 2021-11-24 14:21
I'm not sure what you mean, can you elaborate on what you have tried that is still not working for you?

**Comment by ssalam21** [comment] 2021-11-24 14:26
I tried to read the .gwf files with gwpy. So I've installed gwpy, astropy in conda environment. I've checked my $PYTHONPATH= ~/Fr/Python/ while astropy path  is `~/miniconda3/envs/myenv/lib/python3.9/site-packages/astropy/io/registry/__init__.py.`. Is is a problem? I'm not sure. when I write the script 

`from gwpy.timeseries import TimeSeries
#from obspy.core.trace import Trace
from gwpy.time import from_gps
from astropy.time import Time
#from obspy.core.utcdatetime import UTCDateTime
#from obspy.signal.trigger import classic_sta_lta, trigger_onset
import numpy as np` 

I got the Importerror. I've no idea how to fix it?

**Comment by ssalam21** [comment] 2021-11-24 14:28
I want to play with simple python script but can't execute my script:

`from gwpy.timeseries import TimeSeries
from gwpy.time import from_gps
from astropy.time import Time
import numpy as np

data_dir = '/work/chuck/alamsh/data_CEB/NNC131/NNC-1313060000-1000.gwf'
CEB2_SEIS = ["V1:NN_CEB_ACC_Z_"+str(int(n))for n in np.linspace(201,234,34)]
gwf = TimeSeries.read(data_dir, CEB2_SEIS[0])`

**Comment by ssalam21** [comment] 2021-11-24 14:33
When I start with this `from gwpy.timeseries import TimeSeries` it gives the error below:
`ImportError: cannot import name '_get_valid_format' from 'astropy.io.registry' (~/miniconda3/envs/myenv/lib/python3.9/site-packages/astropy/io/registry/__init__.py)
`

**Comment by ssalam21** [comment] 2021-11-24 14:40
Hi,
Please check the colsed issue #1437.

Regards,
Shariful

**Comment by duncanmmacleod** [comment] 2021-11-24 14:44
Hi, ok, I understand what you are trying and why it doesn't work. However, the bug has been fixed in the git repository, so I have closed the issue. A new version of GWpy that includes the fix has not been released yet, however I hope to get to that before the end of this week.

**Comment by ssalam21** [comment] 2021-11-24 14:54
Ohh, great. Hope to get it soon. Thank you very much for quick response.
