### ISSUE TITLE
Weird parameters to q-transform crashes python interpreter

### ISSUE THREAD

**Issue by areeda** [gwpy/gwpy#464] opened 2017-05-20 19:42 UTC
I was trying to write a test case for the new Q transform in gwpy-plot. I think there is only one second of test data available so I tried to use that. I doubt this is a real use case but the fact that it crashes the Python interpreter with segmentation
[qtest.zip](https://github.com/gwpy/gwpy/files/1016456/qtest.zip)

 fault suggests we should look into it.

Attached is a test program that demonstrates the problem with Python 27 on my Mac. It doesn't crash on a head node but it does hang consuming a lot of CPU and memory.

**Comment by duncanmmacleod** [comment] 2017-06-09 10:44
hi @areeda, thanks for the report. The problem is that the default `fftlength` used to whiten the data is 2 seconds, and you're only giving a 1-second-long `TimeSeries`. This should be fixed.

**Closed** 2017-06-13 08:15 UTC
Labels: gwpy.signal, gwpy.timeseries, in-progress, issue-bug
